### ISSUE TITLE
Streaming parser

### ISSUE THREAD

**Issue by jelmer** [mtreinish/subunit-rust#15]
It would be great if the parser would iterate oven events rather than read all of them at once.

**Comment by mtreinish** [comment]
Is this a duplicate of https://github.com/mtreinish/subunit-rust/issues/5 ?

**Comment by jelmer** [comment]
It's a slightly different problem, but indeed probably fixed by the same change.

**Comment by rbtcollins** [comment]
I have a patch mostly done, doing some code golf - should get back to it next weekend.

**Comment by rbtcollins** [comment]
https://github.com/rbtcollins/subunit-rust/commit/8288090ac801dac4519a0d4207a35108bb493ca5 - theres a few patches to take, I'll make the PRs as rapidly as @mtreinish chooses to review them :)
